In [1]:
import csv
import math
import numpy as np
import random
from matplotlib import pyplot as plt
from IPython.display import Image
data = []
with open('dims.txt') as csvfile:
    points = csv.reader(csvfile,delimiter=',')
    for point_str in points:
        data.append(point_str)
data=np.array(data).astype(np.float)

data

array([[-1.98793769, -0.74538471, -0.17029177, -0.09803062],
       [-1.42961762, -1.46092472, -1.21433657, -3.45998017],
       [ 1.80783608,  0.67599408,  0.97147546, -0.18889123],
       [ 3.29772301,  2.10358676,  2.62706108,  3.05998598],
       [-0.75943517,  0.79793136,  0.83288684,  2.22314027],
       [-2.23485798,  0.03902535, -0.17455733,  0.92476861],
       [ 1.71141252,  0.69028557,  1.25537412,  0.48962121],
       [ 0.01959636, -0.18458676, -0.15380813, -1.51179925],
       [-4.2019328 , -2.13935218, -1.60571136, -2.14884214],
       [ 4.72157406,  3.12058589,  2.75853392,  2.91607966],
       [ 2.69293979,  1.270206  ,  1.22523812,  0.0277424 ],
       [-3.38353061, -1.69356337, -1.42517573, -2.16038433],
       [ 3.39635393,  2.45595154,  2.32148217,  2.70256192],
       [-1.32594826, -0.74166322, -0.06301759, -0.54175005],
       [-0.99746067,  0.70941161,  0.84752415,  2.40192054],
       [ 3.51386292,  2.12831706,  1.84642452,  1.30730312],
       [-1.0583326 , -1.

In [55]:
def distance(X,Y):
    d = 0
    if len(X) != len(Y):
        print 'error!'
    else:
        for index,x in enumerate(X):
            d += (X[index] - Y[index])**2
    return math.sqrt(d)            

In [81]:
def choose_distant_objects(O,D,iterations = 5):
    b = random.randint(0,N-1)
    while iterations > 0:
        a = farthest(b,D)
        b = farthest(a,D)
        iterations -= 1
    return (a,b)

In [58]:
def farthest(index,D):
    distance = -1
    farthest_index = -1
    for i in range(len(D[index])):
        if D[index][i] > distance:
            distance = D[index][i]
            farthest_index = i
    return farthest_index

In [71]:
def FastMap(k,D,O):
    global X
    global col_num
    global PA
    (a,b) = choose_distant_objects(O,D)
    PA[0][col_num] = a
    PA[1][col_num] = b
    print PA
    if D[a][b] == 0:
        for row in X:
            row[col_num] = 0
        return
    else:
        for index,obj in enumerate(X):
            obj[col_num] = (D[a][index]**2 +
                           D[a][b]**2   -
                           D[b][index]**2) / (2* D[a][b])
    if k-1 <= 0:
        return
    else:
        new_D = np.zeros((N,N))
        for i in range(N):
            for j in range(N):
                xi = (D[a][i]**2 +
                               D[a][b]**2   -
                               D[b][i]**2) / (2* D[a][b])
                xj = (D[a][j]**2 +
                               D[a][b]**2   -
                               D[b][j]**2) / (2* D[a][b])
                new_D[i][j] = math.sqrt(D[i][j]**2 -np.round(xi-xj,5)**2)
        col_num += 1
        FastMap((k-1),new_D,O)

In [72]:
#initialize distance metrix
D = np.zeros((N,N))
for i in range(N):
    for j in range(N):
        D[i][j] = distance(data[i],data[j])

In [85]:
#reduced dimention k 
k=2
#number of objects
N = len(data)
#final array of reduced dimention objects
X = np.zeros((N,k))
#store the id of pivot objects
PA = np.zeros((2,k))
#points to the column of X[] array currrently being updated
col_num = 0

In [86]:
FastMap(k,D,data)

[[ 19.   0.]
 [  8.   0.]]
[[ 19.  29.]
 [  8.  66.]]


In [87]:
X

array([[ 10.79881631,   1.33818737],
       [ 12.87853813,   4.30656486],
       [  7.39287498,   3.8114612 ],
       [  3.53501937,   2.22647714],
       [  7.76411769,   0.3218993 ],
       [ 10.07083843,   0.40221119],
       [  6.99618006,   3.21903387],
       [  9.99820426,   3.7135077 ],
       [ 14.4023521 ,   1.53238884],
       [  2.19899862,   3.25334147],
       [  6.3605512 ,   4.20843763],
       [ 13.62365446,   2.06305605],
       [  3.60512709,   2.57792141],
       [ 10.56963111,   2.09898299],
       [  7.85743139,   0.03092469],
       [  4.56924905,   3.73789829],
       [ 12.13941152,   4.17879312],
       [ 10.3109372 ,   1.19719446],
       [  6.96171776,   2.55225127],
       [  0.        ,   1.5323979 ],
       [  5.42119381,   0.31478564],
       [  8.08868527,   0.5904978 ],
       [  8.0804612 ,   2.39576987],
       [  9.08112446,   1.54683102],
       [  1.10242579,   1.01290771],
       [  8.90281701,   0.92926506],
       [ 10.39408515,   0.35417055],
 

array([[ 10.79881631,   3.45278381],
       [ 12.87853813,   0.48440632],
       [  7.39287498,   0.97950998],
       [  3.53501937,   2.56449404],
       [  7.76411769,   4.46907188],
       [ 10.07083843,   4.38875998],
       [  6.99618006,   1.5719373 ],
       [  9.99820426,   1.07746348],
       [ 14.4023521 ,   3.25858234],
       [  2.19899862,   1.53762971],
       [  6.3605512 ,   0.58253355],
       [ 13.62365446,   2.72791513],
       [  3.60512709,   2.21304977],
       [ 10.56963111,   2.69198819],
       [  7.85743139,   4.76004649],
       [  4.56924905,   1.05307288],
       [ 12.13941152,   0.61217806],
       [ 10.3109372 ,   3.59377672],
       [  6.96171776,   2.23871991],
       [  0.        ,   3.25857328],
       [  5.42119381,   4.47618554],
       [  8.08868527,   4.20047338],
       [  8.0804612 ,   2.39520131],
       [  9.08112446,   3.24414016],
       [  1.10242579,   3.77806347],
       [  8.90281701,   3.86170612],
       [ 10.39408515,   4.43680062],
 