In [1]:
import csv
import math
import numpy as np
import random
from matplotlib import pyplot as plt
from IPython.display import Image
data = []
with open('dims.txt') as csvfile:
    points = csv.reader(csvfile,delimiter=',')
    for point_str in points:
        data.append(point_str)
data=np.array(data).astype(np.float)
data

array([[-1.98793769, -0.74538471, -0.17029177, -0.09803062],
       [-1.42961762, -1.46092472, -1.21433657, -3.45998017],
       [ 1.80783608,  0.67599408,  0.97147546, -0.18889123],
       [ 3.29772301,  2.10358676,  2.62706108,  3.05998598],
       [-0.75943517,  0.79793136,  0.83288684,  2.22314027],
       [-2.23485798,  0.03902535, -0.17455733,  0.92476861],
       [ 1.71141252,  0.69028557,  1.25537412,  0.48962121],
       [ 0.01959636, -0.18458676, -0.15380813, -1.51179925],
       [-4.2019328 , -2.13935218, -1.60571136, -2.14884214],
       [ 4.72157406,  3.12058589,  2.75853392,  2.91607966],
       [ 2.69293979,  1.270206  ,  1.22523812,  0.0277424 ],
       [-3.38353061, -1.69356337, -1.42517573, -2.16038433],
       [ 3.39635393,  2.45595154,  2.32148217,  2.70256192],
       [-1.32594826, -0.74166322, -0.06301759, -0.54175005],
       [-0.99746067,  0.70941161,  0.84752415,  2.40192054],
       [ 3.51386292,  2.12831706,  1.84642452,  1.30730312],
       [-1.0583326 , -1.

In [3]:
#Compute the mean vector
mean_v =[]
for i in range(len(data.T)):
    mean_v.append(np.mean(data.T[i]))

In [4]:
mean_v

[0.91473025465000002,
 0.90609110353000011,
 0.91627530581999961,
 0.82391145891999984]

In [6]:
#Compute the covariance matrix
cov_mat = np.cov(data.T)

In [7]:
cov_mat

array([[ 4.44791479,  2.74483743,  2.2486726 ,  2.79426785],
       [ 2.74483743,  2.17666469,  1.64106293,  2.71395314],
       [ 2.2486726 ,  1.64106293,  1.39917388,  2.1907381 ],
       [ 2.79426785,  2.71395314,  2.1907381 ,  4.30116149]])

In [8]:
#Compute eigenvalue and eigenvector of cov_mat
eig_val, eig_vec = np.linalg.eig(cov_mat)

In [9]:
eig_val, eig_vec

(array([  1.06293757e+01,   1.57973675e+00,   9.45183303e-16,
          1.15802423e-01]),
 array([[ 0.5871257 ,  0.70346768, -0.37796447,  0.13251222],
        [ 0.44447908, -0.01493583,  0.37796448, -0.8120087 ],
        [ 0.35827357,  0.00392202,  0.75592894,  0.54790154],
        [ 0.57390052, -0.71055947, -0.37796447,  0.15128216]]))

In [10]:
#Choose 2 eigenvectors with the largest eigenvalues
eig_pairs = [(np.abs(eig_val[i]), eig_vec[:,i]) for i in range(len(eig_val))]

In [12]:
eig_pairs.sort()
eig_pairs.reverse()

In [20]:
W =[]
W.append(eig_pairs[0][1].T)
W.append(eig_pairs[1][1].T)

In [23]:
W = np.array(W)

In [25]:
W

array([[ 0.5871257 ,  0.44447908,  0.35827357,  0.57390052],
       [ 0.70346768, -0.01493583,  0.00392202, -0.71055947]])

In [33]:
dim_reduced_data = W.dot(data.T).T
np.set_printoptions(suppress=True)
dim_reduced_data

array([[-1.61574808, -1.31832829],
       [-3.90946485,  1.46988934],
       [ 1.60154146,  1.39968632],
       [ 5.56851234,  0.12442414],
       [ 1.48304259, -2.12256263],
       [-0.82661069, -2.23052095],
       [ 2.042393  ,  0.85063203],
       [-0.9932672 ,  1.0901624 ],
       [-5.2264656 , -1.40338844],
       [ 6.82104205,  1.21363724],
       [ 2.60056597,  1.86051732],
       [-4.48975975, -0.8254177 ],
       [ 5.46843316,  0.4413175 ],
       [-1.44164026, -0.53698593],
       [ 1.41179278, -2.41566037],
       [ 4.42085868,  1.51842594],
       [-3.16378357,  1.39135958],
       [-1.12036629, -1.43260474],
       [ 2.12347791,  0.17658046],
       [ 9.13671511, -0.36022892],
       [ 3.82076551, -1.95588606],
       [ 1.13837995, -1.88704922],
       [ 1.01720426, -0.07282666],
       [ 0.08058236, -0.99518512],
       [ 8.07734725, -0.94427922],
       [ 0.30811058, -1.56862601],
       [-1.13897732, -2.26122805],
       [ 3.52661928, -1.12029305],
       [ 1.68019578,