In [12]:
import csv
import numpy as np
import math
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import Image
data = []
with open('linear.txt') as csvfile:
    points = csv.reader(csvfile,delimiter=',')
    for point_str in points:
        data.append(point_str)
data=np.array(data).astype(np.float)
data = np.delete(data, np.s_[3:5], axis=1)
data

array([[ 16.83413438,   2.25005563,  43.9896702 ],
       [ 16.16018143,   2.52837564,  49.40866435],
       [ 14.80749844,   2.2651013 ,  41.67188983],
       [ 14.33371275,   1.29106839,  37.98458148],
       [ 13.23638125,   1.00369145,  34.31885796],
       [ 15.96362121,   2.39582104,  46.49306587],
       [ 15.0271781 ,   2.26970918,  37.42651635],
       [ 13.79970165,   1.241663  ,  35.8448822 ],
       [ 14.7087742 ,   1.15562141,  32.36076251],
       [ 13.67476111,   1.34204643,  38.98913119],
       [ 16.00677836,   2.35912361,  42.84991323],
       [ 14.47340337,   2.34436439,  44.79137388],
       [ 16.76727118,   1.8413657 ,  41.36070084],
       [ 13.06869016,   1.84365927,  37.32692994],
       [ 16.31622364,   1.27203654,  45.09736224],
       [ 15.5063639 ,   2.09826712,  37.8836692 ],
       [ 15.15498606,   2.29251589,  38.01981226],
       [ 15.60203054,   1.58317811,  35.74295387],
       [ 15.90651813,   1.59243122,  42.99754629],
       [ 13.37795426,   1.63132

In [95]:
fig = plt.figure()
ax = fig.gca(projection='3d')
for index,point in enumerate(data):
    ax.scatter(point[0], point[1], point[2],c='blue')
    ax.scatter(point[0], point[1],Y_estimate[index],c='red')
plt.show()

In [33]:
#independent data X
X  = np.delete(data, np.s_[2:3], axis=1)
#add constant
X = np.append(X,(np.zeros(len(X)) + 1).T.reshape(50,1),axis=1)
X

array([[ 16.83413438,   2.25005563,   1.        ],
       [ 16.16018143,   2.52837564,   1.        ],
       [ 14.80749844,   2.2651013 ,   1.        ],
       [ 14.33371275,   1.29106839,   1.        ],
       [ 13.23638125,   1.00369145,   1.        ],
       [ 15.96362121,   2.39582104,   1.        ],
       [ 15.0271781 ,   2.26970918,   1.        ],
       [ 13.79970165,   1.241663  ,   1.        ],
       [ 14.7087742 ,   1.15562141,   1.        ],
       [ 13.67476111,   1.34204643,   1.        ],
       [ 16.00677836,   2.35912361,   1.        ],
       [ 14.47340337,   2.34436439,   1.        ],
       [ 16.76727118,   1.8413657 ,   1.        ],
       [ 13.06869016,   1.84365927,   1.        ],
       [ 16.31622364,   1.27203654,   1.        ],
       [ 15.5063639 ,   2.09826712,   1.        ],
       [ 15.15498606,   2.29251589,   1.        ],
       [ 15.60203054,   1.58317811,   1.        ],
       [ 15.90651813,   1.59243122,   1.        ],
       [ 13.37795426,   1.63132

In [18]:
#dependent data Y
Y = np.delete(data, np.s_[0:2], axis=1)
Y

array([[ 43.9896702 ],
       [ 49.40866435],
       [ 41.67188983],
       [ 37.98458148],
       [ 34.31885796],
       [ 46.49306587],
       [ 37.42651635],
       [ 35.8448822 ],
       [ 32.36076251],
       [ 38.98913119],
       [ 42.84991323],
       [ 44.79137388],
       [ 41.36070084],
       [ 37.32692994],
       [ 45.09736224],
       [ 37.8836692 ],
       [ 38.01981226],
       [ 35.74295387],
       [ 42.99754629],
       [ 37.26749304],
       [ 37.19320532],
       [ 40.28035321],
       [ 42.5622431 ],
       [ 36.20966146],
       [ 40.88071942],
       [ 30.78960944],
       [ 44.85476174],
       [ 33.87583968],
       [ 35.3768487 ],
       [ 37.68067805],
       [ 29.46169916],
       [ 46.59871791],
       [ 38.60027091],
       [ 46.2708356 ],
       [ 40.7877692 ],
       [ 43.71580953],
       [ 39.62515232],
       [ 46.30830161],
       [ 38.65297997],
       [ 33.26956138],
       [ 29.71400913],
       [ 49.28618133],
       [ 43.16456568],
       [ 36

In [34]:
beta = np.zeros(X.shape[1])
beta

array([ 0.,  0.,  0.])

In [35]:
def h(beta,X):
    return X.dot(beta.T)

In [43]:
def calc_cost(beta,X,Y):
    return np.mean(Y - h(beta,X))**2

In [77]:
def gd(beta, X, Y, rate=.0001, converge=.0001):
    cost_iter = []
    cost = calc_cost(beta, X, Y)
    cost_iter.append([0, cost])
    cost_diff = 1
    i = 1
    while(cost_diff > converge):
        old_cost = cost
        beta = beta - (rate * X.T .dot ( X.dot(beta) - Y.squeeze()))
        cost = calc_cost(beta, X, Y)
        cost_iter.append([i, cost])
        cost_diff = old_cost - cost
        i+=1
    return beta, ("iterations: ",i)

In [80]:
gd(beta, X, Y,0.0001,0.1)

(array([ 2.58250737,  0.33034043,  0.17125008]), ('iterations: ', 5))

In [81]:
gd(beta, X, Y,0.0001,0.01)

(array([ 2.58358401,  0.33781109,  0.17148698]), ('iterations: ', 6))

In [91]:
gd(beta, X, Y,0.000001,0.001)[0]

array([ 2.57099771,  0.3330856 ,  0.17058185])

In [66]:
Y.squeeze() - X.dot(beta.T)

array([ 43.9896702 ,  49.40866435,  41.67188983,  37.98458148,
        34.31885796,  46.49306587,  37.42651635,  35.8448822 ,
        32.36076251,  38.98913119,  42.84991323,  44.79137388,
        41.36070084,  37.32692994,  45.09736224,  37.8836692 ,
        38.01981226,  35.74295387,  42.99754629,  37.26749304,
        37.19320532,  40.28035321,  42.5622431 ,  36.20966146,
        40.88071942,  30.78960944,  44.85476174,  33.87583968,
        35.3768487 ,  37.68067805,  29.46169916,  46.59871791,
        38.60027091,  46.2708356 ,  40.7877692 ,  43.71580953,
        39.62515232,  46.30830161,  38.65297997,  33.26956138,
        29.71400913,  49.28618133,  43.16456568,  36.17809232,
        42.02067216,  43.86173437,  36.33657516,  42.94316968,
        40.29607123,  33.81800719])

In [53]:
X.T .dot ( X.dot(beta) - Y)

array([[-29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484, -29987.40012484, -29987.40012484,
        -29987.40012484, -29987.40012484],
       [ -3567.13357925,  -3567.13357925,  -3

In [93]:
Y_estimate=h(gd(beta, X, Y,0.000001,0.001)[0],X)

In [96]:
Y_estimate

array([ 44.2005639 ,  42.5605368 ,  38.99509904,  37.45256078,
        34.53560288,  42.0110289 ,  39.56142976,  36.06316324,
        38.37172746,  35.77537767,  42.10976244,  38.16254277,
        43.89253003,  34.38425066,  42.5432525 ,  40.73631047,
        39.89762032,  40.81070045,  41.59661942,  35.10864241,
        43.03756216,  34.42432774,  37.45531279,  36.28218873,
        43.85047483,  34.70142424,  40.26208628,  40.4669911 ,
        40.60663183,  42.84565081,  34.49920981,  42.61698232,
        39.31501723,  41.51521683,  36.49265915,  40.03057792,
        41.37960567,  44.09894033,  38.99135414,  35.06369271,
        34.60439449,  40.9501298 ,  42.03887584,  41.15225205,
        38.02604853,  43.80694013,  39.38229101,  43.71626473,
        35.19362556,  36.04607831])